### ISSUE TITLE
aborting setup during `mako push` doesn't re-run it

### ISSUE THREAD

**Issue by senechko** [digitalocean-mako/mako#1]
if i make a mistake during `mako push` initial setup. and want to go back (i cant), so i ctrl-c out to shell... then i re run `mako push` expecting to be asked the questions again, but instead it tries to push my app

```
✓ Nice. Auth added for -> psenechko@digitalocean.com
✓ Where will we be pushing this app: psenechko@digitalocean.com
✓ What should this app be called : dev

Let's configure your app for deployment:
✓ Installing configuration generators
✓ Choose your configuration preference: Automatic...
✓ Golang app detected, is this correct: No
✓ Unable to auto-detect, please choose a language: Php
? Choose a framework: 
  Laravel
  Lumen
  PHP
› Other
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7d144f]

goroutine 1 [running]:
github.com/digitalocean-mako/cli/internal/controller/classic/scaffold.(*ServiceGenerator).generateData(0x0, 0xc00000e028, 0x0)
        /go/cli/internal/controller/classic/scaffold/service.go:148 +0x3f
github.com/digitalocean-mako/cli/internal/controller/classic/scaffold.(*ServiceGenerator).Generate(0x0, 0x977f20, 0xc000370be0)
        /go/cli/internal/controller/classic/scaffold/service.go:117 +0x43
github.com/digitalocean-mako/cli/internal/controller/classic/scaffold.Scaffold.Generate(0xc00007f220, 0x977f20, 0xc000370be0, 0x9728a0, 0xc0002066c0, 0x9763e0, 0xc000357db0, 0x0, 0x0, 0x0, ...)
        /go/cli/internal/controller/classic/scaffold/scaffold.go:196 +0x728
github.com/digitalocean-mako/cli/internal/controller/classic/deploy.(*Deploy).Init(0xc000056580, 0xc0000dc380, 0x11, 0xc0000dc380)
        /go/cli/internal/controller/classic/deploy/init.go:38 +0xc6
github.com/digitalocean-mako/cli/internal/controller/classic/cmd.Push(0xc00007f220, 0xcae970, 0x0, 0x0, 0x8d2831, 0x4)
        /go/cli/internal/controller/classic/cmd/push.go:152 +0x24a
github.com/digitalocean-mako/cli/internal/controller/classic/cmd.NewPushCmd.func1(0xc000089680, 0xcae970, 0x0, 0x0)
        /go/cli/internal/controller/classic/cmd/push.go:72 +0x67
github.com/spf13/cobra.(*Command).execute(0xc000089680, 0xcae970, 0x0, 0x0, 0xc000089680, 0xcae970)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:702 +0x289
github.com/spf13/cobra.(*Command).ExecuteC(0xc000088b40, 0xc000107080, 0x5, 0x5)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
main.main()
        /go/cli/cmd/mako/main.go:81 +0x319
root@mako-2019-09-09:~/dev# mako push

PREPARING APP ENVIRONMENT :: Building app env & platform            ⣽ Processing
--------------------------------------------------------------------------------
▓▓░░░░░░░░░░░░░░░░░░  8% : do.1 - launching Droplet
^C
```
environment: DO $5 droplet with ubuntu 18

**Comment by jonfriesen** [comment]
Thanks for submitting! We will be releasing a new CLI that has a better understanding of what it means when the user `ctrl+c`'s out. I will reach out to you personally when that release is up.
