### ISSUE TITLE
panic while deploying nodejs application from ubuntu 18.03

### ISSUE THREAD

**Issue by senechko** [digitalocean-mako/mako#3]
i have a single `index.js`  file i'm trying to deploy. i have verified i have `docker` installed.
after running `mako push` and answering questions, i get to `Building live Docker image (web)` step and i get a `panic` (see log below)

DO $5 droplet running Ubuntu 18.03
```
root@mako-2019-09-09:~/hi2# mako push
✓ Where will we be pushing this app: psenechko@digitalocean.com
✓ Is this app already live (on Mako)?: No
✓ Name this app : hi2

Let's configure your app for deployment:
✓ Choose your configuration preference: Automatic...
✓ Golang app detected, is this correct: No
✓ Unable to auto-detect, please choose a language: Node
✓ Choose a framework: Node
✓ Use Node 10: Yes
✓ Do you need a database: No

 /\\\ //\\    Success!
// \\\/  \\   ---------------------------------------------------
\\  \\\  //   Your app has been configured for deployment.
 \\//\\\//    Find editable config files in the .mako/deploy/ folder.


> Building live Docker image (web)                          ⣷ Streaming Output :
--------------------------------------------------------------------------------

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x760d60]

goroutine 1 [running]:
time.(*Ticker).Stop(...)
        /usr/local/go/src/time/tick.go:46
github.com/digitalocean-mako/cli/pkg/display.(*ConsoleStreamer).stopTicker(...)
        /go/cli/pkg/display/stream.go:292
github.com/digitalocean-mako/cli/pkg/display.(*ConsoleStreamer).ErrorStream(0xc0000e80f0)
        /go/cli/pkg/display/stream.go:185 +0xd0
github.com/digitalocean-mako/cli/internal/controller/classic/build.DockerfileBuilder.Build(0x7fca394863f0, 0xc00007a4b0, 0xc000292bf8, 0x3, 0xc000231fe0, 0x1a, 0x0, 0x0, 0xc000231f40, 0x17, ...)
        /go/cli/internal/controller/classic/build/dockerfile.go:84 +0x7d7
github.com/digitalocean-mako/cli/internal/controller/classic/deploy.(*Deploy).buildImages(0xc000056d00, 0xc0000dcd80, 0x0, 0x0)
        /go/cli/internal/controller/classic/deploy/build.go:69 +0x1c6
github.com/digitalocean-mako/cli/internal/controller/classic/deploy.(*Deploy).Build(0xc000056d00, 0xc0000dcd80, 0x0, 0x0)
        /go/cli/internal/controller/classic/deploy/build.go:22 +0x60
github.com/digitalocean-mako/cli/internal/controller/classic/cmd.Push(0xc00007f220, 0xcae970, 0x0, 0x0, 0x8d2831, 0x4)
        /go/cli/internal/controller/classic/cmd/push.go:157 +0x275
github.com/digitalocean-mako/cli/internal/controller/classic/cmd.NewPushCmd.func1(0xc000089680, 0xcae970, 0x0, 0x0)
        /go/cli/internal/controller/classic/cmd/push.go:72 +0x67
github.com/spf13/cobra.(*Command).execute(0xc000089680, 0xcae970, 0x0, 0x0, 0xc000089680, 0xcae970)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:702 +0x289
github.com/spf13/cobra.(*Command).ExecuteC(0xc000088b40, 0xc000107080, 0x5, 0x5)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
main.main()
        /go/cli/cmd/mako/main.go:81 +0x319
root@mako-2019-09-09:~/hi2#
```

**Comment by senechko** [comment]
i have also run into this problem when using a node application with package.json. in this case: https://github.com/gokulkrishh/demo-progressive-web-app

**Comment by senechko** [comment]
spoke with @jonfriesen this was diagnosed by running
```
docker ps
``` 
on the droplet. it turns out i ran `apt install docker` but i really need to run `apt install docker.io`

**Comment by jonfriesen** [comment]
@senechko has posted the correct solution. Later version of our mako CLI should detect docker correctly.
